### PR TITLE
Update providers.yml

### PR DESCRIPTION
**Pull request by mschuchard**
Adding my two linters here.

As a side note, the consensus seems to be that none of the other puppet parser linters work (there is another in addition to the two others listed here).  This is why I made my own in the first place.  Does anyone know if the other two listed on this webpage actually work?

---
This change is [Reviewable](https://reviewable.io/reviews/atomlinter/atomlinter.github.io/41)

### CODE REVIEW

**Comment by keplersj** [comment]
I have no idea. If they aren't working feel free to PR them out.

**Comment by Arcanemagus** [comment]
@mschuchard If [linter-puppet-lint](https://github.com/AtomLinter/linter-puppet-lint) isn't working a PR fixing anything broken would be appreciated! Neither of the two people listed as maintainers have been on in a while, so it looks like it is currently without an active maintainer (but looks like it should be working from the code...).

**Comment by mschuchard** [comment]
Linter-puppet-lint is absolutely working.  Linter-puppet, Linter-puppet-parse, and Linter-puppet-parser are not working as far as I and everyone who has discussed them with me knows.  The latter two are listed on the Atom linter website that is source controlled here.  Those are the ones I was referring to.

**Comment by Arcanemagus** [comment]
Ah, those are external ones that we have no ability to fix.

* [`linter-puppet`](https://github.com/marcelocarlosbr/linter-puppet) isn't listed on the site, looks like it was already removed for not being maintained.
* It looks like [`linter-puppet-parse`](https://github.com/dougbyrne/linter-puppet-parse) is still written for the old API and is guaranteed to be not working. A PR to remove this would be nice :wink:.
* [`linter-puppet-parser`](https://github.com/asquelt/linter-puppet-parser) has nothing glaringly wrong with the code, other than managing process execution themselves. Has anyone tried filing an issue on that repo?

**Pull request merged**
