### PR TITLE
[WIP] Derive from the Material Design

### PR DESCRIPTION
**Pull request by kepler0**
Using [Material Design Lite](http://www.getmdl.io/) we can easily create a style derived from Google's Material Design.

Solves #17.

[Review on Reviewable](https://reviewable.io/reviews/atomlinter/atomlinter.github.io/18)

### CODE REVIEW

**Comment by Arcanemagus** [comment]
The device testing bar is still visible at the top.

**Comment by kepler0** [comment]
Screenshot?

**Comment by Arcanemagus** [comment]
I think I need to stop looking at issues for tonight: Apparently opening Developer Tools in Canary now inserts a bar at the top of the page that exposes all the tools there...

**Comment by kepler0** [comment]
:grinning:

**Comment by steelbrain** [comment]
:+1:

**Pull request merged**
