### PR TITLE
add linter-swift-package-manager

### PR DESCRIPTION
**Pull request by pk11**
this is a linter for the new Swift Package Manager (aka SPM).

[Review on Reviewable](https://reviewable.io/reviews/atomlinter/atomlinter.github.io/26)

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Thanks for the heads up, adding :wink:.

**Comment by Arcanemagus** [comment]
So two things, which I'll remember to check in the future...

* You linked to GitHub, not your Atom package page, which leads to...
* Your package doesn't appear to be published on APM? https://atom.io/packages/linter-swift-package-manager is a 404.

I'll be reverting this for now, once your package is published can you submit another PR linking to the Atom page?

**Comment by pk11** [comment]
@Arcanemagus sorry about the confusion, I am new to Atom. Let me try to add it.

**Comment by pk11** [comment]
@Arcanemagus published the module and created a new PR https://github.com/AtomLinter/atomlinter.github.io/pull/28

**Comment by Arcanemagus** [comment]
Awesome, thanks!

And everyone starts somewhere, if you have any questions Atom's Slack channels are a great place to get started. We have one dedicated to linter plugin development.

**Pull request merged**
