### PR TITLE
New AtomLinter logo.

### PR DESCRIPTION
**Pull request by kepler0**
This is the new AtomLinter logo. It is based on the EmojiOne Shirt sprite with elements representing Atom and the Linter project.

Conversation continuing from AtomLinter/atom-linter#43

[Review on Reviewable](https://reviewable.io/reviews/atomlinter/atomlinter.github.io/11)

### CODE REVIEW

**Comment by k2b6s9j** [comment]
This is really my first attempt attempt at vector graphics and Inkscape, so please be gentle with me as I learn this. I'm open to comments and suggestions as I create this new logo. However it will not be good to merge until all the main contributors to Linter like the way it looks.

**Comment by steelbrain** [comment]
@k2b6s9j the shirt vector is nice, but how many linters do you know that have a shirt logo? IMO it could be something better than a shirt :D

**Comment by k2b6s9j** [comment]
I like the shirt vector much better than any other idea I had. I like what it represents as well, by @AsaAyers's description.

**Comment by k2b6s9j** [comment]
Sure, the shirt is a little abstract. But given that the Atom community is an extension of the GitHub community I think it makes sense.

**Comment by AsaAyers** [comment]
So far over 27 days, a shirt has been the only suggestion. If you want something better than a shirt, come up with a suggestion.

**Comment by k2b6s9j** [comment]
Remember the Atom badge everyone got for contributing to pre-1.0 Atom? I'm going to put that on the shirt.

**Comment by steelbrain** [comment]
Okay then, You have my vote to use a shirt until someone gives a better idea. I am out of ideas myself. Besides I am not a designer anyway :D

**Comment by k2b6s9j** [comment]
I'm trying to decide how best to incorporate the shirt with the Atom logo. So I need some opinions:

- Should the shirt be given a dark outline and made the nucleus of the Atom logo?
- Should the Atom logo be placed as a patch or emblem on the shirt (possibly in place of the buttons)?
- Or am I headed in the wrong direction and be doing something else?

**Comment by kepler0** [comment]
I've decided to base the logo on Emoji's provided by EmojiOne.

How's it look?


[logo](https://github.com/AtomLinter/atomlinter.github.io/blob/new-logo/img/logo.svg)

**Comment by kepler0** [comment]
Not to shabby.

screen shot 2015-11-20 at 10 58 01 pm

I'd say this is ready to go.

Whatcha say? @steelbrain @AsaAyers @joefitzgerald

**Comment by Arcanemagus** [comment]
That looks amazing to me, you have my vote :+1:

**Comment by steelbrain** [comment]
It's beautiful :+1:

**Comment by AsaAyers** [comment]
:+1:

**Comment by steelbrain** [comment]
Just a side note, have you tried replacing that shirt in the logo with a tick mark? I wonder how that would look like

**Comment by kepler0** [comment]
@steelbrain I'd prefer the shirt. Think of it as an homage to the name itself. You lint your code, much like you'd lint a shirt clean.

**Comment by steelbrain** [comment]
Reviewed 1 of 3 files at r1, 1 of 3 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/atomlinter/atomlinter.github.io/11)_

**Comment by steelbrain** [comment]
I am down with it either way

**Comment by kepler0** [comment]
:shipit:

**Comment by SpainTrain** [comment]
:+1: Looks great!  Nice work, my inkscape drawings look like a child made them (actually kids could do better :grin: )

**Pull request merged**
