### PR TITLE
redesign

### PR DESCRIPTION
**Pull request by chadluo**
A redesign of the home page, which is gonna look like this:

image

---
This change is [Reviewable](https://reviewable.io/reviews/atomlinter/atomlinter.github.io/36)

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Why does the site need a redesign in the first place?

That being said, my thoughts on this:

* That title font is absolutely terrible, you want people to be able to quickly read it not look at it, then look again, then go "Oh yea, that's that crazy cursive that I may or may not have been taught in grade school and _never used again_." (depending on how old they are).

* Why are you cutting out almost 1/3 of the content area for a section header when most of the content is in a single section?

* I personally prefer the cards for each language, your approach has too much separation between the headers and the actual linters, stretching the association between the two. (It's still able to be figured out, it's just not _clear_).

I'll leave this to @keplersj for an actual decision, but as it stands if it were up to me I see absolutely no reason for this to be merged.

**Comment by chadluo** [comment]
Why do we need a redesign? Because it is uncomfortable.

I think the current version used MDL to build a modern and clear view, however it did not reach the goal. Titles too big, elements lack adequate spaces. It is too condensed to breath at vital places, but is meaninglessly generous about spaces at irrelevant places. The cards are wide enough to occupy the full width of the page, forcing me to scan from the very left end to the very right end, line by line. That is way too long travel distance, but makes no good.

Why am I using this font for the title? No it is not a title, it is a description, or a slogan. You can use Roboto elsewhere, but you cannot use it here for a slogan. A slogan is not a rational component and It does not match with the whole atmosphere, and it should be treated in a more impressive and persuasive way.

Why am I pushing the links to the right? Because they cannot be that wide. You are not saving any space, the size of a webpage is infinite. But it's not about saving space, it's about being structured and clear, never lost in navigation. A visually compact but unusable navigation simply means nothing. You can have a look at [what I have done](https://github.com/chadluo/atomlinter.github.io/blob/master/_includes/nav.html#L19-L21) to see how I made use of the drawer and improved the navigation.

I understand your preference about cards, but you cannot use it where it does not suit, or use it without limitations. The [official guide](https://www.google.com/design/spec/components/cards.html) suggested a card for a single item, not a list of links, even a list of buttons. To make it worse, the drop shadow does not fit with the scale of the components. The drop shadow is making it worse. You have dozens of cards on the page, and applying drop shadows makes it heavy, complicated, and hard to navigate. You cannot WordArt everything like an amateur MS Word user.

**Comment by keplersj** [comment]
I appreciate your desire to create a design for this page which makes more sense for its purpose. However, I cannot merge this pull request. It's just too big and changes too many things in the page without the commits to express these changes separately and properly. I like the direction in which you wish to go with this updated design, however it would be much more appreciated if you created issues in this repo for each of your gripes in the design so we can create a discussion and act from there. When we are then finished discussing the design gripes at hand we would be happy to accept pull requests addressing these issues.

Allow me reiterate this, Thank You for wanting to create a better design we just can't accept big changes like this.

**Comment by keplersj** [comment]
In order to show that I wish to incorporate more of your design knowledge I have invited you to as a contributor on this repo, in order to work closer together on this change.

**Comment by chadluo** [comment]
Thank you @keplersj for inviting me, and it is really a pleasure to be part of the team.

I agree with your idea that this single PR contains too much changes and it puts a lot of pressure accept them all at once. I will be fine separating them into single and independent issues and having them discussed before pushed up.

**Pull request closed without merging**
