### PR TITLE
added linter-elixir-credo under the elixir category

### PR DESCRIPTION
**Pull request by smeevil**
This change is [Reviewable](https://reviewable.io/reviews/atomlinter/atomlinter.github.io/47)

### CODE REVIEW

**Comment by smeevil** [comment]
Why has this been closed if I may ask ? Is something missing or wrong ?

**Comment by Arcanemagus** [comment]
Good question, `linter-elixir` should probably be added there as well.

**Comment by keplersj** [comment]
Whoops sorry. Hit the wrong button.

**Comment by keplersj** [comment]
I have no idea how that happened. Thanks for asking, I wouldn't have noticed otherwise.

**Pull request merged**
